spring:
  application:
    name: "checkout-service"
  zipkin:
    base-url: http://localhost:9411

server:
  port: 0

logging:
  config: classpath:logback-spring.xml

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka/"