version: '3.5'

services:

  eureka:
    build:
      context: ./registry-service
    container_name: eureka
    hostname: eureka
    ports:
      - "8761:8761"
    networks:
      - store

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    networks:
      - store

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8083:8080"
    networks:
      - store

  checkout-service:
    build:
      context: ./checkout-service
    container_name: checkout-service
    ports:
      - "8082:8080"
    networks:
      - store

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "8081:8080"
    networks:
      - store

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - store

  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - store

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    volumes:
      - ./kibana/config:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - store

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      JAVA_OPTIONS: "-Xmx80m"
    ports:
      - "9411:9411"
    depends_on:
      - elasticsearch
    networks:
      - store

networks:
  store: