version: '3.5'

services:

  discovery:
    build:
      context: ./registry-service
    container_name: discovery
    ports:
      - "8761:8761"

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8083:8080"

  checkout-service:
    build:
      context: ./checkout-service
    container_name: checkout-service
    ports:
      - "8082:8080"

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "8081:8080"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      JAVA_OPTIONS: "-Xmx80m"
    ports:
      - "9411:9411"
      
  grafana:
    build: ./grafana
    container_name: grafana
    mem_limit: 256M
    ports:
      - "3000:3000"

#  prometheus:
#    build: ./prometheus
#    container_name: prometheus
#    mem_limit: 256M
#    ports:
#    - 9091:9090