# config file version
apiVersion: 1

# list of datasources to insert/update depending what's available in the database
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  org_id: 1
  url: http://prometheus:9090
  is_default: true
  version: 1
  editable: true

- name: Zipkin
  type: zipkin
  access: proxy
  org_id: 1
  url: http://zipkin:9411
  password: ""
  user: ""
  database: ""
  basicAuth: false
  is_default: true
  version: 1
  editable: true
