spring:
  application:
    name: "payment-service"
  zipkin:
    base-url: http://zipkin:9411

server:
  port: 0

logging:
  config: classpath:logback-spring.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/