spring:
  application:
    name: "payment-service"
  zipkin:
    base-url: http://zipkin:9411

server:
  port: 0

logging:
  config: classpath:logback-spring.xml

eureka:
  client:
    service-url:
      default-zone: http://eureka:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true